version: '3.8'

services:
  cypress:
    image: cypress/included:latest
    container_name: cypress-tests
    networks:
      - booking-challenge_default  # Ensure it's on the same network
    environment:
      - CYPRESS_baseUrl=http://booking-app:80
    volumes:
      - .:/e2e
    working_dir: /e2e

  booking-app:
    image: nginx:alpine
    container_name: booking-app
    networks:
      - booking-challenge_default  # Ensure it's on the same network
    ports:
      - "80:80"

networks:
  booking-challenge_default:
    driver: bridge  # Docker Compose will create this network
