version: '3.8'

networks:
  test-network:
    driver: bridge

services:
  booking-app:
    build: .  # Use your own application build instead of nginx:alpine
    container_name: booking-app
    entrypoint: ["/bin/sh", "-c", "./start.sh && tail -f /dev/null"]  # Run start.sh at container start
    volumes:
      - .:/app
    networks:
      - test-network
    depends_on:
      - booking-php-fpm
    ports:
      - "8000:80"

  booking-php-fpm:
    image: booking-challenge_php-fpm
    container_name: booking-php-fpm
    volumes:
      - ./php-fpm:/var/www/html
    networks:
      - test-network

  cypress-tests:
    build: .  # Cypress container
    container_name: cypress-tests
    depends_on:
      booking-app:
        condition: service_started  # Ensure booking-app is started first
    networks:
      - test-network
    environment:
      - CYPRESS_baseUrl=http://booking-app:80
    volumes:
      - .:/e2e
    working_dir: /e2e
    command: ["npx", "cypress", "run", "--config", "baseUrl=http://booking-app:80"]
