version: '3.8'

networks:
  test-network:
    driver: bridge

services:
  booking-app:
    build: .  # Ensures your application is built from the local Dockerfile
    container_name: booking-app
    networks:
      - test-network  # Ensure booking-app is attached to test-network
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  cypress-tests:
    build: .  # Ensures Cypress uses your custom Dockerfile
    depends_on:
      booking-app:
        condition: service_healthy  # Ensures Cypress waits for booking-app to be ready
    networks:
      - test-network
    environment:
      - CYPRESS_baseUrl=http://localhost:8000
    volumes:
      - .:/e2e
    working_dir: /e2e
    command: ["npx", "cypress", "run", "--config", "baseUrl=http://localhost:8000"]
