version: '3.8'

networks:
  test-network:
    driver: bridge

services:
  booking-app:
    image: nginx:alpine
    container_name: booking-app
    networks:
      - test-network  # Ensure booking-app is attached to test-network
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  cypress:
    image: cypress/included:latest
    container_name: cypress-tests
    networks:
      - test-network # Ensure cypress-tests is attached to test-network
    environment:
      - CYPRESS_baseUrl=http://booking-app:80
    volumes:
      - .:/e2e
    working_dir: /e2e
#    entrypoint: [ "sh", "-c", "apk add --no-cache curl && until curl -s http://booking-app:80; do sleep 2; done && npm run test" ]
