version: '3.8'

networks:
  test-network:  # Define the network here, do NOT use "external"
    driver: bridge

services:
  booking-app:
    image: nginx:alpine
    container_name: booking-app
    ports:
      - "8000:80"
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  cypress:
    image: cypress/included:latest
    container_name: cypress-tests
    networks:
      - test-network
    environment:
      - CYPRESS_baseUrl=http://booking-app:80
    volumes:
      - .:/e2e
    working_dir: /e2e
    entrypoint: ["sh", "-c", "until curl -s http://booking-app:80; do sleep 2; done && npm run test"]
