version: '3.8'

networks:
  test-network:
    driver: bridge

services:
  booking-app:
    image: nginx:alpine
    container_name: booking-app
    networks:
      - test-network  # Ensure booking-app is attached to test-network
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://booking-app:80"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  cypress-tests:  # Updated service name to match Dockerfile
    build: .  # This ensures Cypress uses your custom Dockerfile
    container_name: cypress-tests
    depends_on:
      booking-app:
        condition: service_healthy  # Ensures Cypress waits for booking-app to be ready
    networks:
      - test-network  # Ensure cypress-tests is attached to test-network
    environment:
      - CYPRESS_baseUrl=http://booking-app:80
    volumes:
      - .:/e2e
    working_dir: /e2e
    command: ["npx", "cypress", "run", "--config", "baseUrl=http://booking-app:80"]

