version: '3.8'

networks:
  test-network:
    driver: bridge

services:
  booking-app:
    build: .  # Assuming your app has a Dockerfile
    container_name: booking-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php-fpm:/var/www/html
    depends_on:
      - booking-php-fpm
    ports:
      - "8000:80"

  booking-php-fpm:
    image: booking-challenge_php-fpm
#    container_name: booking-php-fpm
    volumes:
      - ./php-fpm:/var/www/html
    networks:
      - test-network

  cypress-tests:
    build: .  # This ensures Cypress uses your custom Dockerfile
    depends_on:
      - booking-app
    networks:
      - test-network
    environment:
      - CYPRESS_baseUrl=http://booking-app:80
    volumes:
      - .:/e2e
    working_dir: /e2e
    entrypoint: ["/bin/sh", "-c"]  # Change entrypoint to allow script execution
    command: ["./start.sh && npx cypress run --config baseUrl=http://booking-app:80"]
