name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      # Start the local application server
      - name: Start Application Server
        run: npm start &  # Ensure this runs in the background

      # Install Ngrok
      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      # Start Ngrok to expose localhost:8000
      - name: Start Ngrok Tunnel
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok http 8000 > /dev/null &  # Start Ngrok in the background
          sleep 5  # Give Ngrok time to initialize
          echo "Fetching Ngrok public URL..."
          curl --silent http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' > ngrok_url.txt
          cat ngrok_url.txt  # Show the generated public URL
          echo "CYPRESS_BASE_URL=$(cat ngrok_url.txt)" >> $GITHUB_ENV

      # Run Cypress Tests using the Ngrok public URL
      - name: Run Cypress Tests
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: ${{ env.CYPRESS_BASE_URL }}

      # Upload Cypress test results
      - name: Upload Cypress Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/videos/
