name: Cypress Tests

on: [push, pull_request]  # Run tests on every push and pull request

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start application server
        run: npm start &

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run Cypress tests in Docker
        run: |
          docker build -t cypress-tests .
          docker-compose up cypress

      - name: Upload Cypress test results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/videos/
