name: Run Cypress Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Start Application
        run: |
#          ./start.sh > server.log 2>&1 &  # Start the server in the background
#          sleep 5                         # Short wait to allow process to initialize

      - name: Debug Running Processes
        run: ps aux  # Check if the server process is running

#      - name: Check Open Ports
#        run: sudo lsof -i :8000


      - name: Verify Server is Running
        run: curl --fail http://0.0.0.0:8000 || (echo "Server did not start!" && exit 1)

#      - name: Display Server Logs (if failed)
#        if: failure()
#        run: cat server.log

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/results/
