name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

#      - name: Set up Docker Compose
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y docker-compose

#      - name: Build and Start the Application
#        run: |
#          docker-compose up -d  # Start the app in detached mode
#          sleep 15  # Wait for the app to start
#
#      - name: Check Running Containers
#        run: docker ps  # Debugging step to ensure containers are running
      - name: Debug Running Containers
        run: docker ps -a

      - name: Test Application (Check if it's running)
        run: curl -f http://localhost:8000

      - name: Run Cypress Tests
        run: docker-compose run cypress-tests  # Runs Cypress inside Docker

      - name: Upload Cypress test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/videos/
